### ISSUE TITLE
How to install the native app

### ISSUE THREAD

**Issue by Mte90** [M-Reimer/midiinputprovider#1]
First of all I love this project!
I was looking for something like that (I found this the other day https://addons.mozilla.org/en-US/firefox/addon/jazz-midi/?src=cb-dl-created) and I want to try asap.
In the readme is not explained how to install the native app, 
I have to put on /usr/local/bin?

I want to use my midi piano like a synthesizer so I was thinking to create an html app but without api is impossible!

**Comment by M-Reimer** [comment]
After cloning change to the "nativeapp" directory and run "make install" or "make userinstall". You can just use "make" to get some information about this Makefile.

I've used this web synthesizer for debugging and at least this one works with my Addon:
http://webmididemo.herokuapp.com/

**Comment by Mte90** [comment]
Maybe add that information in the readme can simplify and involve more people in this project :-)
PS: thanks for the hints :-)
